"""JavaScript interview questions database"""

JS_QUESTIONS = [
    "What is the difference between let, var, and const in JavaScript?",
    "Explain event bubbling and event capturing in JavaScript.",
    "What are closures in JavaScript and how do they work?",
    "What is the difference between == and === in JavaScript?",
    "Explain the concept of hoisting in JavaScript.",
    "What are JavaScript promises and how do they work?",
    "What is the difference between function declarations and function expressions?",
    "Explain the 'this' keyword in JavaScript.",
    "What are JavaScript prototypes and prototype chain?",
    "What is event delegation in JavaScript?",
    "Explain the difference between synchronous and asynchronous JavaScript.",
    "What are JavaScript callbacks and callback hell?",
    "What is the JavaScript event loop?",
    "Explain the concept of scope in JavaScript.",
    "What are JavaScript arrow functions and how are they different from regular functions?",
    "What is destructuring in JavaScript?",
    "Explain the concept of modules in JavaScript.",
    "What are JavaScript generators?",
    "What is the difference between null and undefined?",
    "Explain the concept of inheritance in JavaScript.",
    "What are JavaScript higher-order functions?",
    "What is the difference between call, apply, and bind methods?",
    "Explain the concept of currying in JavaScript.",
    "What are JavaScript template literals?",
    "What is the spread operator in JavaScript?",
    "Explain the concept of debouncing and throttling.",
    "What are JavaScript Web APIs?",
    "What is the difference between localStorage and sessionStorage?",
    "Explain the concept of CORS in JavaScript.",
    "What are JavaScript regular expressions?",
    "What is the difference between map, filter, and reduce methods?",
    "Explain the concept of memoization in JavaScript.",
    "What are JavaScript classes and how do they work?",
    "What is the difference between setTimeout and setInterval?",
    "Explain the concept of strict mode in JavaScript.",
    "What are JavaScript symbols?",
    "What is the difference between deep copy and shallow copy?",
    "Explain the concept of JavaScript engines.",
    "What are JavaScript iterators and iterables?",
    "What is the difference between Object.freeze() and Object.seal()?",
    "Explain the concept of JavaScript decorators.",
    "What are JavaScript mixins?",
    "What is the difference between function.call() and function.apply()?",
    "Explain the concept of JavaScript modules (ES6 modules).",
    "What are JavaScript getters and setters?",
    "What is the difference between for...in and for...of loops?",
    "Explain the concept of JavaScript error handling with try-catch.",
    "What are JavaScript typed arrays?",
    "What is the difference between Object.create() and new Object()?",
    "Explain the concept of JavaScript weak references (WeakMap, WeakSet)."
]